SELECT [SourceOrganization]
      ,[ExchangeGuid]
      ,[ExternalDirectoryObjectID]
      ,[Guid]
      ,[Alias]
      ,[DisplayName]
      ,[PrimarySmtpAddress]
      ,[RecipientTypeDetails]
      ,[Role]
      ,[TargetGroupGUID]
      ,[TargetGroupExternalDirectoryObjectID]
      ,[TargetGroupDisplayName]
      ,[TargetGroupPrimarySmtpAddress]
      ,[Action]
      ,[TargetOrganization]
FROM [Point32Health].[dbo].[qIDistributionGroupRole]